---
- hosts: all
  tasks:
          # - name: clone vim config
          #   git:
          #     repo: https://github.com/masters-of-cats/a-new-hope
          #     dest: ~/.config/nvim
          #     force: yes
          #
  - name: install vim plugins and binaries
    command: nvim --headless +PlugInstall +PlugUpdate +GoUpdateBinaries +qall

  - name: update remote plugins
    command: nvim --headless +UpdateRemotePlugins +qall

  - name: Check if oh-my-zsh is installed
    stat: path=~/.oh-my-zsh
    register: ohmyzsh

  - name: install oh-my-zsh unless already installed
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when: not ohmyzsh.stat.exists

  - name: install concourse-flake-hunter
    command: go get -u github.com/masters-of-cats/concourse-flake-hunter

  - name: install counterfeiter
    command: go get -u github.com/maxbrunsfeld/counterfeiter

  - name: get TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - file: path=~/bin state=directory mode=0755

  - name: set up symlinks
    file:
      path: "{{item.target}}"
      src: "{{item.src}}"
      state: link
      force: yes
    with_items:
    - {target: ~/.oh-my-zsh/custom/env.zsh, src: "{{ansible_env.PWD}}/config/bash/env.bash"}
    - {target: ~/.oh-my-zsh/custom/git.zsh, src: "{{ansible_env.PWD}}/config/bash/git.bash"}
    - {target: ~/.oh-my-zsh/custom/ngrok.zsh, src: "{{ansible_env.PWD}}/config/bash/ngrok.bash"}
    - {target: ~/.oh-my-zsh/custom/aliases.zsh, src: "{{ansible_env.PWD}}/config/bash/aliases.bash"}
    - {target: ~/.git-authors, src: "{{ansible_env.PWD}}/config/.git-authors"}
    - {target: ~/.gitconfig-shared, src: "{{ansible_env.PWD}}/config/.gitconfig-shared"}
    - {target: ~/.ruby-version, src: "{{ansible_env.PWD}}/config/.ruby-version"}
    - {target: ~/.tmate.conf, src: "{{ansible_env.PWD}}/config/tmate.conf"}
    - {target: ~/.tmux.conf, src: "{{ansible_env.PWD}}/config/tmux.conf"}
    - {target: ~/bin/load-key, src: "{{ansible_env.PWD}}/executables/load-key"}
    - {target: ~/bin/flake-hunter, src: "{{ansible_env.PWD}}/executables/flake-hunter"}

  - name: ~/.gitconfig
    blockinfile:
      path: ~/.gitconfig
      create: yes
      block: |
        [include]
          path = ~/.gitconfig-shared

  - name: install git-co-authored-by-hook
    environment:
      GIT_DUET_CO_AUTHORED_BY: 1
    command: bash -c "git solo \"$( grep authors -A 1 ~/.git-authors | tail -1 | cut -d ':' -f 1 | tr -d '[:space:]' )\""
