---
- hosts: all
  tasks:
  - name: update brew
    homebrew: update_homebrew=yes

  - name: add Homebrew taps
    homebrew_tap: name={{item}}
    with_items:
    - homebrew/cask-fonts
    - cloudfoundry/tap
    - git-duet/tap
    - neovim/neovim

  - name: install Homebrew packages
    homebrew:
      name:
      - ack
      - ag
      - awscli
      - bash
      - bash-completion@2
      - bosh-cli
      - cf-cli
      - chruby
      - ruby-install
      - coreutils
      - ctags
      - curl
      - direnv
      - docker
      - docker-machine
      - fasd
      - fortune
      - fzf
      - git
      - git-duet
      - go
      - htop
      - jq
      - jsonpp
      - lastpass-cli
      - libgit2
      - kubectl
      - neovim
      - npm
      - pstree
      - python3
      - python@2
      - ripgrep
      - shellcheck
      - ssh-copy-id
      - terraform
      - tig
      - tmate
      - tmux
      - tree
      - vim
      - watch
      - wget
      - yarn
      - zsh
      state: latest

  - name: install Homebrew casks
    homebrew_cask: name={{item}} install_options=appdir=/Applications
    with_items:
    - docker
    - flycut
    - font-inconsolata
    - font-inconsolata-nerd-font
    - google-cloud-sdk
    - iterm2
    - shiftit
    - ngrok

  - name: install neovim pip package
    pip: name=neovim state=latest

  - name: install neovim pip3 package
    pip: name=neovim state=latest executable=/usr/local/bin/pip3
